### ISSUE TITLE
Build from master branch fails

### ISSUE THREAD

**Issue by nicolaasjan** [mpv-player/mpv-build#164] opened 2021-08-28 18:54 UTC
Linux Mint 19.3 64bit

Output:

```bash
../demux/demux_lavf.c: In function 'update_read_stats':
../demux/demux_lavf.c:273:31: error: 'AVIOContext {aka struct AVIOContext}' has no member named 'bytes_read'
         int64_t cur = nest->id->bytes_read;
                               ^~

Waf: Leaving directory `/media/ext3-data/git/mpv-build/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1: 
	{task 139792330092440: c demux_lavf.c -> demux_lavf.c.21.o}
['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-format-truncation', '-Wimplicit-fallthrough', '-fno-math-errno', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-I.', '-I..', '-I../../build_libs/include', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/fribidi', '-I/usr/include/lua5.2', '-I/usr/include/libdrm', '-I/usr/include/alsa', '-I/usr/include/uchardet', '-I/usr/include/libxml2', '-D_REENTRANT', '../demux/demux_lavf.c', '-c', '-o/media/ext3-data/git/mpv-build/mpv/build/demux/demux_lavf.c.21.o']
```

Any ideas?

**Comment by sfan5** [comment] 2021-08-28 18:56
duplicate of https://github.com/mpv-player/mpv/issues/9159, check there for a workaround

**Closed by sfan5** 2021-08-28 18:56 UTC

**Comment by nicolaasjan** [comment] 2021-08-28 19:01
Well, that was fast.
Thanks!
I did a search first for "AVIOContext", but couldn't find anything.
