### ISSUE TITLE
mpv-build-deps breaks apt-get on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by marlencrabapple** [mpv-player/mpv-build#57] opened 2015-03-01 03:50 UTC
Tried running `mk-build-deps -s sudo -i` on Ubuntu 14.04.2. I thought it might have been some sort of conflict with a PPA that forced me to do a partial upgrade, so to make sure I tried it again on a fresh install but had the same problem.

Also more of an Ubuntu 14.04.2 bug, but apt-get can install dependencies for `libgl1-mesa-dev`.

```
dpkg-deb: building package `mpv-build-deps' in `../mpv-build-deps_2015.02.28.a76cc1d_amd64.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package mpv-build-deps.
(Reading database ... 215171 files and directories currently installed.)
Preparing to unpack mpv-build-deps_2015.02.28.a76cc1d_amd64.deb ...
Unpacking mpv-build-deps (2:2015.02.28.a76cc1d) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... failed.
The following packages have unmet dependencies:
 mpv-build-deps : Depends: autoconf but it is not installed
                  Depends: automake but it is not installed
                  Depends: ladspa-sdk but it is not installed
                  Depends: libasound2-dev but it is not installed
                  Depends: libbluray-dev but it is not installed
                  Depends: libbs2b-dev but it is not installed
                  Depends: libcaca-dev but it is not installed
                  Depends: libcdio-paranoia-dev but it is not installed
                  Depends: libdvdnav-dev but it is not installed
                  Depends: libdvdread-dev but it is not installed
                  Depends: libegl1-mesa-dev
                  Depends: libenca-dev but it is not installed
                  Depends: libfontconfig-dev
                  Depends: libfreetype6-dev but it is not installed
                  Depends: libfribidi-dev but it is not installed
                  Depends: libgl1-mesa-dev
                  Depends: libgnutls-dev but it is not installed or
                           libgnutls28-dev but it is not installed
                  Depends: libgsm1-dev but it is not installed
                  Depends: libguess-dev but it is not installed
                  Depends: libjack-jackd2-dev but it is not installed or
                           libjack-dev
                  Depends: libjpeg-dev
                  Depends: libopenjpeg-dev but it is not installed
                  Depends: liblcms2-dev but it is not installed
                  Depends: liblircclient-dev but it is not installed
                  Depends: liblua5.1-0-dev but it is not installed
                  Depends: liblua5.2-dev but it is not installed
                  Depends: libmp3lame-dev but it is not installed
                  Depends: libmpg123-dev but it is not installed
                  Depends: libopus-dev but it is not installed
                  Depends: libopencore-amrnb-dev but it is not installed
                  Depends: libopencore-amrwb-dev but it is not installed
                  Depends: libpulse-dev but it is not installed
                  Depends: librubberband-dev but it is not installed
                  Depends: libschroedinger-dev but it is not installed
                  Depends: libsmbclient-dev but it is not installed
                  Depends: libspeex-dev but it is not installed
                  Depends: libtheora-dev but it is not installed
                  Depends: libtool
                  Depends: libtwolame-dev but it is not installed
                  Depends: libv4l-dev but it is not installed
                  Depends: libva-dev but it is not installed
                  Depends: libvdpau-dev but it is not installed
                  Depends: libvorbis-dev but it is not installed
                  Depends: libvo-aacenc-dev but it is not installed
                  Depends: libvo-amrwbenc-dev but it is not installed
                  Depends: libvpx-dev but it is not installed
                  Depends: libwavpack-dev but it is not installed
                  Depends: libx264-dev but it is not installed
                  Depends: libx11-dev but it is not installed
                  Depends: libxext-dev but it is not installed
                  Depends: libxinerama-dev but it is not installed
                  Depends: libxrandr-dev but it is not installed
                  Depends: libxss-dev but it is not installed
                  Depends: libxv-dev but it is not installed
                  Depends: libxvmc-dev but it is not installed
                  Depends: libxvidcore-dev but it is not installed
                  Depends: python-docutils but it is not installed
                  Depends: rst2pdf but it is not installed
                  Depends: x11proto-core-dev but it is not installed
                  Depends: yasm but it is not installed
                  Depends: zlib1g-dev but it is not installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: Unable to correct dependencies
install call failed
```

**Comment by marlencrabapple** [comment] 2015-03-01 04:44
Also more of an Ubuntu 14.04.2 bug, but apt-get can install dependencies for `libgl1-mesa-dev`.

**Comment by kevmitch** [comment] 2015-03-02 00:28
Works for me in my trusty chroot with /etc/apt/sources.list

    deb http://mirror.its.sfu.ca/mirror/ubuntu trusty main restricted universe multiverse
    deb http://mirror.its.sfu.ca/mirror/ubuntu trusty-updates main restricted universe multiverse

A lot of the dependencies are in universe, some maybe even in multiverse. Do you have these repositories selected? You can see/change with the software-properties-gtk GUI.

**Comment by marlencrabapple** [comment] 2015-03-02 07:47
Yeah they're definitely selected. Its a 14.04.2 issue, so it might not apply to your setup unless you've opted in to the update. Turns out the root of the problem is certain dev packages not having resolved dependencies in 14.04.2, which is not an mpv issue. The fact that installing this package completely breaks apt-get until its uninstalled is still kind of worrying though. Not sure if there's anything to be done about it though, so unless someone thinks otherwise there's probably no reason for this to stay open any longer.

**Comment by kevmitch** [comment] 2015-03-04 00:30
I'm not exactly sure how Ubuntu handles their point releases. I had assumed that having trusty-updates selected would include that. What does your sources.list look like? 

Do you know which packages are causing the problem? Unfortunately, apt is really bad about telling you what the actual problem is in the case that one of the dependencies is unsatisfiable. You typically have to try installing the dependencies one by one without the mpv-build-deps package until you encounter the problem.

If a package with unsatisfied dependencies is installed, then yes apt will complain / possibly not work until that's either resolved or the package is uninstalled. That's just the way apt works. I'm sure some would argue it's a feature not a bug.

**Comment by kevmitch** [comment] 2015-03-15 07:12
[fixed in ubuntu](https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1424466)

**Closed by kevmitch** 2015-03-15 07:12 UTC
