### ISSUE TITLE
Isn't it cuda support of debian rule not yet!

### ISSUE THREAD

**Issue by workman729** [mpv-player/mpv-build#91] opened 2017-10-04 06:15 UTC
I have a question?

mpv-build use by direct compile of correct support nvidia cuda.
But, use by debian rule is not a support nvidia cuda.

Of course ppa offer in correct support original source tarball of ppa:mc3man/mpv-tests.
He's a lot of modification by config script!

So, i was some modif config.
This is ffmpeg options.

 echo --enable-gnutls \
--enable-libopencore-amrnb \
--enable-libopencore-amrwb \
--enable-libvo-amrwbenc \
--enable-librtmp \
--enable-libgme \
--enable-libgsm \
--enable-libmodplug \
--enable-libmp3lame \
--enable-libfdk-aac \
--enable-libass \
--enable-libopus \
--enable-libpulse \
--enable-libsoxr \
--enable-libspeex \
--enable-libssh \
--enable-libtheora \
--enable-libtwolame \
--enable-libvorbis \
--enable-libvpx \
--enable-libwavpack \
--enable-libopenjpeg \
--enable-ladspa \
--enable-libbs2b \
--enable-gpl \
--enable-libxvid \
--enable-libx264 \
--enable-libx265 \
--enable-libopenh264 \
--enable-libfribidi \
--enable-libopenjpeg \
--enable-libopus \
--enable-libpulse \
--enable-libfreetype \
--enable-fontconfig \
--enable-libtwolame \
--enable-libv4l2 \
--enable-openal \
--enable-opencl \
--enable-sdl2 \
--enable-opengl \
--enable-libwebp \
--enable-nonfree \
--enable-pic \
--enable-nvenc \
--enable-cuda \
--enable-cuvid \
--enable-libnpp \
--extra-cflags=-I/usr/include/nvenc \
--extra-cflags=-I/usr/include/cuda \
--enable-version3 \
>> ffmpeg_options

As by magic, use i was make fedora spec file of correct nvidia cuda.
 I wonder to know what a different.

Thanks.

**Comment by kevmitch** [comment] 2017-10-05 00:03
So the issue is that cuda doesn't work if you build mpv-build debian package. I guess I'm not surprised as I've done nothing to make this work since I don't have nvidia to test. Are you saying you need --enable-cuvid on ffmpeg command line? I'm not sure if there's anything that could / should be done about --extra-cflags if that's really necessary.

**Comment by workman729** [comment] 2017-10-05 04:20
Well, agree. My old habit, the location distinct to some case!

It's not should be necessary, i do personally analysis from ppa source.
Thanks a lot.

**Comment by wm4** [comment] 2017-10-05 12:31
Can't tell what you mean. But cuvid is autodetected and basically always on in ffmpeg and mpv. But you should probably use mpv and ffmpeg git master, as the releases tend to be mismatched.

**Comment by workman729** [comment] 2017-10-06 03:44
I know that cuvid autodected, it's doesn't matter git master and release.
Always same options are not detected by only use debian rules, but use build and  rebuild compile correct detected.

So, i will ask a question.

**Comment by kevmitch** [comment] 2017-12-01 08:26
The debian package has more ffmpeg options enabled than `./build`. And in any case @wm4 says extra options shouldn't be necessary. Both methods are equally exposed to system libraries (unless you've done something to isolate the debian build). Both should also make use of `/usr/local/` anarchy. There don't seem to be obvious configure state differences and I don't have the hardware to test if my binaries actually work with cuda. 

Did you say you were using `debuild`? I only ever use `dpkg-buildpackage` because it does fewer unnecessary things.

**Comment by workman729** [comment] 2017-12-07 13:54
Is that so! I will test your suggest that.

**Comment by workman729** [comment] 2017-12-13 12:25
I think, it started matter right location with nvidia cuvid library.

Well, ubuntu nvidia driver is always missing symbolic link libnvcuvid library, so i make myself put in /usr/lib/x86_64-linux-gnu.

I guess libnvcuvid.so link right location is /usr/lib/nvidia-38x, i think be connected alternatives link x86_64-linux-gnu_GL.conf

So, this issue is from my mistake, forgive me.

**Comment by kevmitch** [comment] 2017-12-13 12:36
Ok, I'm not exactly sure what the problem is, but my understanding is that you've figured out what might be going on, so closing.

**Closed by kevmitch** 2017-12-13 12:36 UTC
